### ISSUE TITLE
marc21 indexing  - to be discussed.

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-records-marc21#5]
needs to be changed - to be discussed. 
```suggestion
    "marcid": dict(
```

_Originally posted by @mb-wali in https://github.com/tu-graz-library/invenio-records-marc21/pull/3#discussion_r554894624_

**Comment by utnapischtim** [comment]
- is this used somewhere?
- could this produce some naming conflicts with invenio-records-ui or other modules from inveniosoftware?
- the cookiecutter template does not indicate that this has to be customized?
