### ISSUE TITLE
**MISSING entrypoints** for jsonschema and mappings.

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-records-marc21#6]
**MISSING entrypoints** for jsonschema and mappings.

_Originally posted by @mb-wali in https://github.com/tu-graz-library/invenio-records-marc21/pull/3#discussion_r554897797_

**Comment by utnapischtim** [comment]
for now we trust in dojson to create a valid marc21 json. BUT for the long run we have to invest time into that. specifically in the mappings part, because otherwise we would have no search possibilities
